# Generated by Django 4.0.1 on 2022-01-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='52830', max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=160),
        ),
    ]
