# Generated by Django 4.0.1 on 2022-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_slug_news_url_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='147779', max_length=80),
        ),
    ]
