# Generated by Django 3.2.9 on 2022-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='552133', max_length=80),
        ),
    ]
