# Generated by Django 3.2.9 on 2022-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220131_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milan_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='content', max_length=160)),
                ('content', models.TextField(default='content')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(default='596835', max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='554752', max_length=80),
        ),
    ]
