# Generated by Django 3.2.9 on 2022-02-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220204_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='club',
            field=models.CharField(default='*', max_length=160),
        ),
        migrations.AlterField(
            model_name='milan_news',
            name='url',
            field=models.CharField(default='965966', max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='482814', max_length=80),
        ),
    ]
