# Generated by Django 3.2.9 on 2022-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220205_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milan_news',
            name='url',
            field=models.CharField(default='837749', max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='742087', max_length=80),
        ),
    ]
