# Generated by Django 3.2.9 on 2022-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220205_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='logo_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='milan_news',
            name='url',
            field=models.CharField(default='287382', max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='263623', max_length=80),
        ),
    ]
