# Generated by Django 3.2.9 on 2022-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220205_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='club',
            field=models.CharField(default='*', max_length=299),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='896859', max_length=80),
        ),
    ]
