# Generated by Django 3.2.9 on 2022-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220207_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='logo_url',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='517648', max_length=80),
        ),
    ]
