# Generated by Django 3.2.9 on 2022-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20220207_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_players_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(default='*', max_length=160)),
                ('name', models.CharField(default='*', max_length=160)),
                ('age', models.CharField(default='*', max_length=160)),
                ('position', models.CharField(default='*', max_length=160)),
                ('appearences', models.CharField(default='*', max_length=160)),
                ('total', models.CharField(default='*', max_length=160)),
                ('assists', models.CharField(default='*', max_length=160)),
                ('rating', models.FloatField(default=6.0)),
            ],
        ),
        migrations.CreateModel(
            name='League_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='*', max_length=160)),
                ('rank', models.IntegerField(default=0)),
                ('name', models.CharField(default='*', max_length=160)),
                ('played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('goalsDiff', models.CharField(default='*', max_length=160)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='448312', max_length=80),
        ),
    ]
