# Generated by Django 3.2.9 on 2022-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20220216_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_players_stats',
            name='assists',
            field=models.CharField(default='*', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='42586', max_length=80),
        ),
    ]
